FROM maven
LABEL author="MEL"
LABEL name="PawfectMatch"
ENV LANG C.UTF-8
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn --install
FROM eclipse-temurin:20-jdk-alpine
COPY target/pawfectMatch.jar .
CMD ["java", "-jar", "pawfectMatch.jar"]